### ISSUE TITLE
Directive not working on github but the one on the examples does.

### ISSUE THREAD

**Issue by decklord** [bachvtuan/html5-sortable-angularjs#11]
We where using your directive which is really nice but the code on github is not working. We ended copying the one in the examples and it seems newer than the one in github.

**Comment by bachvtuan** [comment]
You're right.  You seem do this on  #10 .

**Comment by decklord** [comment]
No, I did't update the code, I just added bower.json but the code is still broken (thanks for the fast response by the way)
